; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_deps = 
	bblanchon/ArduinoJson@^6.21.5
	4-20ma/ModbusMaster@^2.0.1
	vshymanskyy/TinyGSM@^0.12.14
	knolleary/PubSubClient@^2.8
	emelianov/modbus-esp8266@^4.1.0
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
build_flags = 
	-DTINY_GSM_MODEM_SIM800
	-DTINY_GSM_RX_BUFFER=256
	
	-DARDUINOJSON_ENABLE_PROGMEM=1
	-DARDUINOJSON_USE_LONG_LONG=1
	
	-std=gnu++14
	-Wall
	-Werror
upload_speed = 115200
board_build.filesystem = littlefs
